### ISSUE TITLE
-f insted of -n for skip prompt?

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/force-source-clean#12]
more consistent with -f as a "force" action for CLIs when you want to ignore warnings

my $.02, obviously a subjective opinion

**Comment by ChuckJonas** [comment]
`--no-prompt` seems more consistent with other `sfdx-cli` commands (see [org:delete](org:delete)).  Although `sfdx-cli` lacks consistency with the shorthand here (so far I see `-n`, `-p` & `-r`.  

To me, `-f` indicates that something about the state of the command is exceptional but you want to do it anyways.  For example with `git`, deleting a branch which is not merged or pushing changes that rewrite history.
