### ISSUE TITLE
Non SFDX File in Package Directory Breaks Clean

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/force-source-clean#4]
```
➜  project git:(XXX.1/master) sfdx force:source:clean -x manifest/package.xml 
(node:22917) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
WARNING: This command can be dangerous! It is intended to be used along side source control.  IT WILL REMOVE ALL FILES FROM 'packageDirectories' WHICH ARE NOT FOUND IN THE TARGET ORG.  They will not be recoverable unless tracked in source control!
Do you wish to continue? (y): y
WARNING: Failed to retrieve! All files are "marked" and will need to be manually reset!
ERROR running force:source:retrieve:  Unexpected file found in package directory: /Users/ralphcallaway/Development/project/src/classes/SomeClass.cls.orig
```

In this case, a git merge conflict artifact broke down the process and left everything deleted (will post some thoughts on that in another ticket)

Not totally sure this is really an issue with this command, more an issue with the sfdx command not being smart enough to tell the difference between sfdx and non-sfdx files in package directories.

**Comment by ralphcallaway** [comment]
added a `.forceignore` with the following and the method runs, but the file gets deleted (fine in this case)

a lot of this boils down to is there a good reason to have non-sfdx files in package folders (kind of feel like now, let's be opinionated and say if it doesn't exist in the org it's deleted, regardless of whether it's an sfdx file our not. package folders are just for sfdx files

**Comment by ralphcallaway** [comment]
it also deletes the old `src/package.xml` manifest, which should go anyway ...

perhaps we make that the description, cleans folder so that it only contains sfdx metadata that are in the current default org

**Comment by ChuckJonas** [comment]
Ya, looks like the error. 

I think we could exclude `.` files and `.forceIgnore`.  EVERYTHING else will be removed.  As you saw before, nothing else should be in the source folders as it will break the standards `sfdx force:source` commands... So by deleting everything else it really is "cleaning up"

**Comment by ChuckJonas** [comment]
I think the only TODO from this issue is just to make this behavior more apparent in the command help and readme.md

**Comment by ralphcallaway** [comment]
mostly, i'd say #6 is a todo that comes out of this, but yeah it seems like you'd expect clean to delete these files and to mirror the current constraints of the sfdx command
