### ISSUE TITLE
Spinner During Clean

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/force-source-clean#5]
After clicking yes, you're waiting for a pretty good while.

Would be a nice place for a super styling spinner or other pacifier

https://github.com/clj-commons/spinner has a lot of options, these two options in the demo seemed perfect
- pointing-fingers (finger rolls across screen)
- some kind of long running processing happens here (randomly uses all the spinners)

**Comment by ChuckJonas** [comment]
`oclif` actually has one built in `this.ux.startSpinner`

**Comment by ChuckJonas** [comment]
added in 0.0.3
