### ISSUE TITLE
Add Command Line Automate to match standard functions

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/force-source-clean#7]
did i a decent amount of autocomplete for our ant scripts, happy to take this on

**Comment by ChuckJonas** [comment]
Not sure I understand exactly  what this issue is for.  When you first opened it, I thought it was for cli autocomplete but looks like that's what #8 is referencing?

**Comment by ralphcallaway** [comment]
#8 was focused on having things work for the -x param, this was broader

not worth focusing on
