### ISSUE TITLE
Support Auto Completing Manifest Name (Ref #17)

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/force-source-clean#8]
Sub case of #17

if i have a file `manifest/package.xml` and i type `sfdx force:source:clean -x m` i'd expect to be able to tab and it would auto complete the file name (default zsh behavior)

not sure if there is something in the sfdx command that supports this

i'm currently using https://github.com/wadewegner/salesforce-cli-zsh-completion which might be the source of the behavior, so may end up being something to add over there

**Comment by ChuckJonas** [comment]
I'm non entirely sure... I know that auto-complete for the standard plugin is provided to zsh via https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/sfdx/_sfdx

I _think_ this is the only reason I get auto-complete when I run `sfdx force:mdapi:deploy -d deploy/...`

We could create something similar, but it will require a manual install (I don't think omgzsh is going to accept something this niche)

**Comment by ralphcallaway** [comment]
oh sweet didn't know the completions were already in a plugin

this isn't worth thinking about, closing this

**Comment by ChuckJonas** [comment]
I think maybe as an alternate solution, we should just default `-x` to `manifest/package.xml`... as this is really the only path that would ever be valid for a typical dev project

**Comment by ralphcallaway** [comment]
love that as a default
